/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorComic;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Sofi
 */
public class GUIComic extends javax.swing.JFrame {
    private ControladorComic controlador;
//    private GUIJuego gUIJuego;
    private GUIInicio gUIInicio;
    private Icon comic1;

    
    public GUIComic(GUIInicio gUIInicio) {
        initComponents();
        this.setSize(820, 535);
        this.setLocation(270, 100);
        this.gUIInicio=gUIInicio;
        controlador= new ControladorComic(this,gUIInicio);
        setControlador();
        comic1=new ImageIcon(getClass().getResource("../icon/comic1.png"));
        setPrimerComic();
        
    }
    
    public void setControlador(){
        jbSig.addActionListener(controlador);
        jbSikp.addActionListener(controlador);
    }
  
    public void setPrimerComic(){
        jlComic.setIcon(comic1);
    }
    
    public Icon getPrimerComic(){
        return comic1;
    }
    
    public void setComicSig(Icon comic){
        jlComic.setIcon(comic);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSikp = new javax.swing.JButton();
        jbSig = new javax.swing.JButton();
        jlComic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jbSikp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/skip.png"))); // NOI18N
        jbSikp.setActionCommand("Skip");
        jbSikp.setContentAreaFilled(false);
        jbSikp.setPreferredSize(new java.awt.Dimension(63, 42));
        getContentPane().add(jbSikp);
        jbSikp.setBounds(130, 420, 63, 42);

        jbSig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/siguiente.png"))); // NOI18N
        jbSig.setActionCommand("Siguiente");
        jbSig.setContentAreaFilled(false);
        jbSig.setPreferredSize(new java.awt.Dimension(63, 42));
        getContentPane().add(jbSig);
        jbSig.setBounds(50, 420, 63, 42);

        jlComic.setText("comic");
        getContentPane().add(jlComic);
        jlComic.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSig;
    private javax.swing.JButton jbSikp;
    private javax.swing.JLabel jlComic;
    // End of variables declaration//GEN-END:variables
}
