/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorFin;
import modelo.ArchivoPuntuacion;
import modelo.Puntuacion;
import modelo.RegistroPuntuacion;

/**
 *
 * @author Sofi
 */
public class GUIFin extends javax.swing.JFrame {
    private GUIInicio gUIInicio;
    private ControladorFin controlador;
    private GUIJuego gUIJuego;
    private RegistroPuntuacion registroPuntuacion;
    private GUIPuntuacion gUIPuntuacion;
    
    public GUIFin(GUIInicio gUIInicio,GUIJuego gUIJuego, GUIPuntuacion gUIPuntuacion) {
        initComponents();
        this.setSize(800, 530);
        this.setLocation(270, 100);
        deshabilitarCampos();
        registroPuntuacion= new RegistroPuntuacion();
        controlador= new ControladorFin(this, gUIInicio,registroPuntuacion,gUIPuntuacion);
        setControlador();
        this.gUIJuego=gUIJuego;
    }

    public void deshabilitarCampos(){
        jtTiempo.setEditable(false);
        jtFrisbe.setEditable(false);
        jtTotal.setEditable(false);
    }
    
    public void setControlador(){
        jbIngresar.addActionListener(controlador);
        jbMenu.addActionListener(controlador);
        jbOtraVez.addActionListener(controlador);
    }
    
    public void setDatos(){
        jtTiempo.setText(""+gUIJuego.tiempoFinal);
        jtFrisbe.setText(""+gUIJuego.cantFrisbe);
        jtTotal.setText(""+gUIJuego.totalPuntos);
    }
    
    public Puntuacion getPuntuacion(){
        return new Puntuacion(Integer.parseInt(jtTotal.getText()), jtNombre.getText());
    }
        
    public String [] getPuntuacionString(){
        String datos[]= new String [2];
        
        datos[0]=jtTotal.getText();
        datos[1]=jtNombre.getText();
        
        return datos;
    }
    
    public String getNombre()
    {
        return jtNombre.getText();
    }
    
    public void limpiar(){
        jtTiempo.setText("");
        jtFrisbe.setText("");
        jtTotal.setText("");
        jtNombre.setText("");
    }
    ///////ARCHIVOS
    
    public void crearArchivo() {
        registroPuntuacion.setPuntuacionArchivo();
    }


    public void getArchivo() {
        registroPuntuacion.getArchivo();
    }
    
    public RegistroPuntuacion getRegistroPuntuacion(){
        return registroPuntuacion;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbMenu = new javax.swing.JButton();
        jbOtraVez = new javax.swing.JButton();
        jbIngresar = new javax.swing.JButton();
        jtTiempo = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtTotal = new javax.swing.JTextField();
        jtFrisbe = new javax.swing.JTextField();
        jlFin = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        jbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        jbMenu.setActionCommand("Menu");
        jbMenu.setContentAreaFilled(false);
        getContentPane().add(jbMenu);
        jbMenu.setBounds(60, 420, 129, 42);

        jbOtraVez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/otraVez.png"))); // NOI18N
        jbOtraVez.setActionCommand("OtraVez");
        jbOtraVez.setContentAreaFilled(false);
        getContentPane().add(jbOtraVez);
        jbOtraVez.setBounds(60, 340, 129, 42);

        jbIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ingresar.png"))); // NOI18N
        jbIngresar.setActionCommand("Ingresar");
        jbIngresar.setContentAreaFilled(false);
        getContentPane().add(jbIngresar);
        jbIngresar.setBounds(580, 430, 129, 42);

        jtTiempo.setFont(new java.awt.Font("where stars shine the brightest", 0, 36)); // NOI18N
        getContentPane().add(jtTiempo);
        jtTiempo.setBounds(640, 60, 110, 40);

        jtNombre.setFont(new java.awt.Font("where stars shine the brightest", 0, 36)); // NOI18N
        getContentPane().add(jtNombre);
        jtNombre.setBounds(640, 300, 110, 40);

        jtTotal.setFont(new java.awt.Font("where stars shine the brightest", 0, 36)); // NOI18N
        getContentPane().add(jtTotal);
        jtTotal.setBounds(640, 210, 110, 40);

        jtFrisbe.setFont(new java.awt.Font("where stars shine the brightest", 0, 36)); // NOI18N
        getContentPane().add(jtFrisbe);
        jtFrisbe.setBounds(640, 130, 80, 40);

        jlFin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fin.png"))); // NOI18N
        getContentPane().add(jlFin);
        jlFin.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
       // crearArchivo();
    }//GEN-LAST:event_formComponentHidden

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIFin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbIngresar;
    private javax.swing.JButton jbMenu;
    private javax.swing.JButton jbOtraVez;
    private javax.swing.JLabel jlFin;
    private javax.swing.JTextField jtFrisbe;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTiempo;
    private javax.swing.JTextField jtTotal;
    // End of variables declaration//GEN-END:variables
}
