/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorMenu;

/**
 *
 * @author Sofi
 */
public class GUIInstrucciones extends javax.swing.JFrame {

    private GUIInicio gUIInicio;
    private ControladorMenu controlador;

    public GUIInstrucciones(GUIInicio gUIInicio) {
        initComponents();
        this.setSize(800, 535);
        this.setLocation(270, 100);
        controlador= new ControladorMenu(gUIInicio, this);
        setControlador();
    }

    public void setControlador(){
        panelBotonesMenu1.setControlador(controlador);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotonesMenu1 = new vista.PanelBotonesMenu();
        jlInstruccionesPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelBotonesMenu1.setOpaque(false);
        panelBotonesMenu1.setPreferredSize(new java.awt.Dimension(129, 42));
        getContentPane().add(panelBotonesMenu1);
        panelBotonesMenu1.setBounds(620, 20, 129, 42);

        jlInstruccionesPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/instruccionesPantalla.png"))); // NOI18N
        getContentPane().add(jlInstruccionesPantalla);
        jlInstruccionesPantalla.setBounds(-10, 10, 790, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlInstruccionesPantalla;
    private vista.PanelBotonesMenu panelBotonesMenu1;
    // End of variables declaration//GEN-END:variables
}
