/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorMenu;

/**
 *
 * @author Sofi
 */
public class GUIPuntuacion extends javax.swing.JFrame {

    private ControladorMenu controlador;
    private GUIInicio gUIInicio;
    
    /**
     * Creates new form GUIPuntuacion
     */
    public GUIPuntuacion(GUIInicio gUIInicio) {
        initComponents();
        this.setSize(800, 515);
        this.setLocation(270, 100);
        controlador= new ControladorMenu(gUIInicio, this);
        setControlador();
    }

    public void setControlador(){
        panelBotonesMenu1.setControlador(controlador);
    }
    

    public void setPrimerNombre(String nombre){
        jlPrimerNombre.setText(nombre);
    }
    
    public void setPrimerPuntaje(int puntaje){
        jlPrimerPuntaje.setText(""+puntaje);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlPrimerPuntaje = new javax.swing.JLabel();
        jlPrimerNombre = new javax.swing.JLabel();
        panelBotonesMenu1 = new vista.PanelBotonesMenu();
        jlPuntuaciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jlPrimerPuntaje.setFont(new java.awt.Font("where stars shine the brightest", 0, 60)); // NOI18N
        jlPrimerPuntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPrimerPuntaje.setText("795");
        jlPrimerPuntaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jlPrimerPuntaje);
        jlPrimerPuntaje.setBounds(200, 290, 130, 50);

        jlPrimerNombre.setFont(new java.awt.Font("where stars shine the brightest", 0, 80)); // NOI18N
        jlPrimerNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPrimerNombre.setText("Sofía");
        jlPrimerNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jlPrimerNombre);
        jlPrimerNombre.setBounds(90, 190, 340, 70);

        panelBotonesMenu1.setOpaque(false);
        getContentPane().add(panelBotonesMenu1);
        panelBotonesMenu1.setBounds(540, 400, 130, 50);

        jlPuntuaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/puntuaciones2.png"))); // NOI18N
        getContentPane().add(jlPuntuaciones);
        jlPuntuaciones.setBounds(0, -10, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlPrimerNombre;
    private javax.swing.JLabel jlPrimerPuntaje;
    private javax.swing.JLabel jlPuntuaciones;
    private vista.PanelBotonesMenu panelBotonesMenu1;
    // End of variables declaration//GEN-END:variables
}
