/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;

/**
 *
 * @author Sofi
 */
public class PanelBotonesMenu extends javax.swing.JPanel {
    
    public PanelBotonesMenu() {
        initComponents();
    }

    public void setControlador(ActionListener controlador){
        jbMenu.addActionListener(controlador);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbMenu = new javax.swing.JButton();

        setLayout(null);

        jbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        jbMenu.setActionCommand("Menu");
        jbMenu.setContentAreaFilled(false);
        jbMenu.setMaximumSize(new java.awt.Dimension(129, 42));
        jbMenu.setMinimumSize(new java.awt.Dimension(129, 42));
        jbMenu.setPreferredSize(new java.awt.Dimension(129, 42));
        jbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuActionPerformed(evt);
            }
        });
        add(jbMenu);
        jbMenu.setBounds(0, 0, 129, 42);
    }// </editor-fold>//GEN-END:initComponents

    private void jbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbMenu;
    // End of variables declaration//GEN-END:variables
}
